services:
  dev:
    ipc: host
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${UID:-9999}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: ${SRC_DATA_DIR}
        target: /home/user/dev/data
        consistency: delegated
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
        consistency: delegated
      - type: bind
        source: .
        target: /home/user/dev
        consistency: delegated
